# -*- coding: utf-8 -*-
"""indexing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y7I9OG8Fyz0F0-7ylGV-Kj-pSnMB32ml
"""

strSample = 'learning'

strSample.index('l')

strSample.index('n')

strSample.index('ning')

strSample[7]

strSample[-2]

'list indexing'

Sample = [1,2,3,'afsar',5]

Sample.index('afsar')

Sample.index(3)

Sample[2]

Sample[-1]

'''array indexing'''

from array import*

Sam = array('i',[1,2,3,4])

for x in Sam :
  print (x)

Sam[-3]

'''tuple indexing'''

tuples = (1,3,3,5,6,'Afsar')

tuples.index('Afsar')

tuples[2]

'''set indexing'''

sets = {2,23.5,5,5,'data','data'}

'''sets does not support indexing'''

'''dictionary does not support indexing'''

dictSample = {1:'Afsar','basha':3,5:'four'}

dictSample[1]

dictSample['basha']

'''range indexing'''

rangeSample = range(1,25,9)

for x in rangeSample:
  print(x)

rangeSample.index(0) '''0 not in range'''

rangeSample.index(10)

rangeSample[2]  #give index value , returns element value

